name: Docker Build
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 23 * * 1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Publish to Dockerhub
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./.github/workflow/ubuntu-latest
        platforms: linux/amd64
        push: true
        tags: risawitama/build:buildbot
        
    - name: send telegram message
      run: |
          function sendTG() {
          curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendmessage" --data "text=${*}&chat_id=${{ secrets.TELEGRAM_TO }}&parse_mode=Markdown"
          }
          sendTG "\`I have pushed new images to docker\` %0A [Image are here](https://hub.docker.com/r/risawitama/build/tags)" &> /dev/null
